### ISSUE TITLE
Question about config

### ISSUE THREAD

**Issue by USA-RedDragon** [resfilter/aldl#9]
Sorry to open a new issue on an old project but I do have a quick question. Does the ALDL interface have the ability to display fuel level? If not I can always use the gpio pins on an RPI to get a number, but if it can read fuel level it can save me some work.

**Comment by resfilter** [comment]
not that I'm aware of... most ecms don't even have fuel level input of any sort.  if it did though im sure you could make it happen

**Comment by USA-RedDragon** [comment]
Didn't think so, but I can always get it from the sensor voltage in the gauge. Thanks a lot!
